services:
  - type: worker
    name: campost-pipeline
    runtime: docker
    plan: free
    branch: dev
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: BACKEND_IMPORT_URL
        sync: false
      - key: IMPORTER_API_TOKEN
        sync: false
      - key: POSTGRES_DB
        sync: false
      - key: POSTGRES_USER
        sync: false
      - key: POSTGRES_PASSWORD
        sync: false
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: 5432
      - key: DB_SSLMODE
        value: require
      - key: CRAWL_INTERVAL_MINUTES
        value: 60
      - key: HEADLESS
        value: true
      - key: GEMINI_API_KEY
        sync: false
      - key: GEMINI_MODEL
        value: gemini-2.5-flash
      - key: R2_ACCOUNT_ID
        sync: false
      - key: R2_ACCESS_KEY_ID
        sync: false
      - key: R2_SECRET_ACCESS_KEY
        sync: false
      - key: R2_BUCKET_NAME
        sync: false
      - key: R2_PUBLIC_URL
        sync: false
